apiVersion: batch/v1
kind: Job
metadata:
  name: static-analysis
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: static-analysis
        image: malware-static:latest
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Never
      restartPolicy: Never
