apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrie
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: cowrie
        image: cowrie:latest
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 2222
